name: 1.0.0
trigger:
  paths:
    exclude:
      - .github
      - .vscode/*
      - Build
pool:
  vmImage: 'windows-latest'
variables:
  ModuleName: NexusIQ

steps:
  - checkout: self
    path: ${{variables.ModuleName}}

  - template: Build/register-psgallery.yml

  # Haven't been able to get the test to work. Mocking doesn't work right.
  # - pwsh: |
  #     $Separator = [System.IO.Path]::DirectorySeparatorChar
  #     $SaveDir = "$env:APPDATA$Separator$env:ModuleName"
  #     $AuthXmlPath = "$SaveDir$Separator`Auth.xml"
  #     [pscredential]@{
  #       BaseUrl = $env:BaseUrl
  #       APIVersion = "V2"
  #       Credential = [pscredential]::new($env:UserCode,$($env:PassCode | ConvertTo-SecureString -AsPlainText -Force))
  #     } | Export-CliXml -Path $AuthXmlPath
  #   displayName: Set up Nexus IQ connection profile
  #   env:
  #     UserCode: TestUserCode
  #     PassCode: TestPassCode
  #     ModuleName: ${{variables.ModuleName}}
  #     BaseUrl: https://nexusiq.myorg.com

  # - template: Build/run-tests.yml
  #   parameters:
  #     ModuleName: ${{variables.ModuleName}}

  - task: PowerShell@2
    displayName: Run the build script
    inputs:
      targetType: filePath
      filePath: ./Build.ps1
      workingDirectory: $(Pipeline.Workspace)/${{parameters.ModuleName}}

  - template: Build/publish-module.yml
    parameters:
      ModuleName: ${{variables.ModuleName}}
